{% set version = "0.1.0" %}

package:
  name: jupyter-panel-proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-panel-proxy/jupyter-panel-proxy-{{ version }}.tar.gz
  sha256: 4d65091afa2fcd07ed16a3da291137e9955a49fa30664fde72a62bd60382a431

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - panel
    - jupyter-server-proxy

test:
  imports:
    - panel

about:
  home: https://github.com/pyviz/jupyter-panel-proxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Jupyter Server Proxy for Panel applications'
  description: |
    When jupyter-panel-proxy is installed and you run `jupyter notebook`,
    you'll find the served version of the panel app at the regular url
    such as `http://localhost:8888` followed by `panel/<name_of_file>`
  dev_url: https://github.com/pyviz/jupyter-panel-proxy

extra:
  recipe-maintainers:
    - jsignell
    - philippjfr
    - ocefpaf
