{% set version = "0.2.0" %}

package:
  name: jupyter-panel-proxy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-panel-proxy/jupyter_panel_proxy-{{ version }}.tar.gz
  sha256: c7b7bed3f09d51325f74498bf231a34739ffea3d0f9f2356ea5c9e2050a1755f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.25.0
    - hatch-vcs >=0.4.0
  run:
    - python >={{ python_min }}
    - panel >=0.11
    - pyyaml
    - jupyter-server-proxy

test:
  requires:
    - python {{ python_min }}
  imports:
    - panel

about:
  home: https://github.com/holoviz/jupyter-panel-proxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Jupyter Server Proxy for Panel applications'
  description: |
    When jupyter-panel-proxy is installed and you run `jupyter notebook`,
    you'll find the served version of the panel app at the regular url
    such as `http://localhost:8888` followed by `panel/<name_of_file>`
  dev_url: https://github.com/holoviz/jupyter-panel-proxy

extra:
  recipe-maintainers:
    - maximlt
    - jsignell
    - philippjfr
    - ocefpaf
